name: Nightly Admin
on:
  schedule:
    - cron: '30 1 * * *'

env:
  GITHUB_TOKEN:      ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN:          ${{ secrets.GITHUB_TOKEN }}

jobs:
  CloseStaleIssues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Stale Issues
        uses: actions/stale@v7
        with:
          stale-issue-message: 'This issue is stale because it has been open 7 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 14 days with no activity.'
          days-before-stale: 7
          days-before-close: 14
          days-before-pr-close: -1
          only-labels: triage,feedback-required
